### ISSUE TITLE
No aparece el castellano en los enlaces para ver la página actual en otros idiomas

### ISSUE THREAD

**Issue by DavidHernandez** [andalugeeks/andaluh-wiki#7]
Supongo que como la web es un proxy de la web en castellano, hace una tradución completa del HTML de la página que visualizamos. Como en el origen en castellano no tiene el enlace de ver el contenido en castellano, al ver la web en andalûh, tampoco aparece el enlace, impidiendo ir a la versión en castellano.

Para los que no hablamos andalûh, nos es costoso ver el original para apreciar de manera sencilla las diferencias.

**Comment by FernanOrtega** [comment]
Hola David. Es muy buen apunte el que has hecho, voy a añadirlo como nueva feature a implementar.

Un saludo.
